# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109IsyIy3gd9mXzAIew55AQv_nugA71jr
"""

import streamlit as st
import pandas as pd
from google import genai
from google.genai import types

st.title("📊 無母數統計 AI Agent")
st.write("上傳你的 CSV 資料，AI 會自動幫你寫程式並跑完無母數檢定。")

# 左側邊欄讓使用者輸入 API Key
api_key = st.secrets["GEMINI_API_KEY"]
# 主畫面提供上傳按鈕
uploaded_file = st.file_uploader("上傳 CSV 檔案", type=["csv"])

if uploaded_file and api_key:
    # 讀取並顯示資料
    df = pd.read_csv(uploaded_file)
    st.write("### 預覽資料", df.head())

# 🌟 新增：讓使用者可以輸入自己的 Prompt
    custom_prompt = st.text_area(
        "請輸入你的具體分析需求（可留白）：", 
        placeholder="例如：請幫我比較 A 與 B 欄位，並畫出小提琴圖...",
        height=100
    )

    # 啟動分析的按鈕
    if st.button("🚀 開始自動分析"):
        with st.spinner("Agent 思考與執行程式碼中..."):
            try:
                client = genai.Client(api_key=api_key)
                csv_string = df.to_csv(index=False)

                sys_instruct = """
                你是一位嚴謹且精通無母數統計學的資深數據顧問。你的任務是接收使用者上傳的資料集，透過編寫與執行 Python 程式碼來完成端到端的無母數統計檢定，並產出具備學術水準的分析報告。

【Agent 思考與執行工作流 SOP】

1. 資料探索與常態性檢定：
   - 檢查資料型態與缺失值。
   - 執行常態性檢定（如 Shapiro-Wilk test 或 Kolmogorov-Smirnov Test），若確認資料不符合常態分佈或為小樣本，則進入無母數檢定流程。

2. 樣本結構分析（嚴格判斷）：
   - 判斷組數：資料是「單樣本（One Sample）」、「雙樣本（Two Samples）」還是「多樣本（Multiple Samples, 3組以上）」。
   - 判斷獨立性：若為雙樣本或多樣本，請從資料結構判斷樣本之間是「獨立（Independent）」還是「配對/相關（Paired/Related）」。

3. 檢定方法決策與執行（依據上述結構選擇）：
   - 單樣本：執行 One Sample Sign Test 或 One Sample Wilcoxon Signed-Rank Test。
   - 兩獨立樣本：執行 Mann Whitney U Test (Wilcoxon Rank Sum Test)。
   - 兩配對樣本：執行 Wilcoxon signed ranks test。
   - 多獨立樣本：執行 Kruskal-Wallis Test。
   - 多配對樣本：執行 Friedman Test。

4. 事後多重比較（Post-hoc Multiple Comparisons）：
   - 若執行 Kruskal-Wallis Test 或 Friedman Test 且結果顯著 (p < 0.05)，你「必須」自動補上事後檢定（如 Dunn's Test 等）。
   - 執行事後檢定時，務必套用 p-value 校正（如 Bonferroni 或 Holm 方法）以避免型一錯誤。

5. 視覺化：
   - 撰寫 Python 程式碼繪製能呈現資料分佈的圖表（推薦盒鬚圖、小提琴圖疊加散佈點）。

【回應格式規範】
產出報告請包含以下區塊：
- 資料結構解析： 說明判斷出的組數（單/雙/多樣本）與獨立性（獨立/配對），以及常態性檢定結果。
- 方法選擇： 說明為何選擇該無母數檢定方法。
- 整體檢定結果： 列出檢定統計量與 P-value。所有統計檢定假設（虛無假設與對立假設）請使用 LaTeX 呈現（例如 $H_0: M_1 = M_2$）。
- 多重比較結果（若有）： 列出事後檢定的各組兩兩比較 P-value（需標註已使用的校正方法）。
- 結論與建議： 用白話文解釋這些數字代表什麼實務或研究意義。
                """
                # 🌟 更新：將資料與使用者的自訂 Prompt 結合
                if custom_prompt.strip() == "":
                    # 如果使用者沒輸入，就用預設指令
                    user_prompt = f"資料如下：\n\n{csv_string}\n\n請依據系統設定的 SOP 進行完整的無母數分析。"
                else:
                    # 如果使用者有輸入，就強制 AI 結合 SOP 與使用者指令
                    user_prompt = f"資料如下：\n\n{csv_string}\n\n【使用者的特別指示】：\n{custom_prompt}\n\n請在滿足上述特別指示的前提下，嚴格遵守系統設定的 SOP 進行分析。"

                response = client.models.generate_content(
                    model="gemini-3.6-flash",
                    contents=user_prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=sys_instruct,
                        tools=[types.Tool(code_execution=types.ToolCodeExecution())],
                    ),
                )

                st.markdown("---")
                st.markdown("### 📝 分析報告")
                st.markdown(response.text)

            except Exception as e:
                st.error(f"發生錯誤：{e}")
