# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109IsyIy3gd9mXzAIew55AQv_nugA71jr
"""

import streamlit as st
import pandas as pd
from google import genai
from google.genai import types

st.title("📊 無母數統計 AI Agent")
st.write("上傳你的 CSV 資料，AI 會自動幫你寫程式並跑完無母數檢定。")

# 左側邊欄讓使用者輸入 API Key
api_key = st.secrets["GEMINI_API_KEY"]
# 主畫面提供上傳按鈕
uploaded_file = st.file_uploader("上傳 CSV 檔案", type=["csv"])

if uploaded_file and api_key:
    # 讀取並顯示資料
    df = pd.read_csv(uploaded_file)
    st.write("### 預覽資料", df.head())

    # 啟動分析的按鈕
    if st.button("🚀 開始自動分析"):
        with st.spinner("Agent 思考與執行程式碼中..."):
            try:
                client = genai.Client(api_key=api_key)
                csv_string = df.to_csv(index=False)

                sys_instruct = """
                你是一位嚴謹的數據顧問。請分析 CSV 資料，使用 Python 執行無母數檢定 (Shapiro-Wilk, Mann-Whitney U 等)。
                請輸出：資料概況、方法選擇、檢定結果 (包含 LaTeX 虛無假設) 與商業建議。
                """
                user_prompt = f"資料如下：\n\n{csv_string}\n\n請執行 SOP。"

                response = client.models.generate_content(
                    model="gemini-3.6-flash",
                    contents=user_prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=sys_instruct,
                        tools=[types.Tool(code_execution=types.ToolCodeExecution())],
                    ),
                )

                st.markdown("---")
                st.markdown("### 📝 分析報告")
                st.markdown(response.text)

            except Exception as e:
                st.error(f"發生錯誤：{e}")
